require('__stdlib__/stdlib/core')

require('prototypes/item-groups')
require('prototypes/electric-poles')
require('prototypes/electric-interfaces')
require('prototypes/infinity-containers')
require('prototypes/pipes')
require('prototypes/lab')
require('prototypes/beacon')
require('prototypes/modules')
require('prototypes/radar')
require('prototypes/loaders')
